title: "【💡 功能请求】"
labels: feature
name: "💡 功能请求"
description: 为这个项目提出一个创意需求
body:
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 描述你的功能需求
      description: |
        提出你的创意和功能想法，如果有参考的实现方法可以贴上链接。
    validations:
      required: true
