name: Check and Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Get package.json version
      id: get_version
      run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

    - name: Get latest release version
      id: get_release
      run: |
        curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name' > latest_release.txt

    - name: Compare versions
      id: compare_versions
      run: |
        if [ "$(cat latest_release.txt)" != "$PACKAGE_VERSION" ]; then
          echo "Version mismatch"
          echo "create_release=true" >> $GITHUB_ENV
        else
          echo "Version matches"
          echo "create_release=false" >> $GITHUB_ENV
        fi

    - name: Create new release
      if: env.create_release == 'true'
      run: |
        CURRENT_DATE=$(TZ='Asia/Shanghai' date +'%Y-%m-%d  %H:%M')
        sed -i "s/\$PACKAGE_VERSION/$PACKAGE_VERSION/g" CHANGELOG.md
        sed -i "s/\$CURRENT_DATE/$CURRENT_DATE/g" CHANGELOG.md
        gh release create "$PACKAGE_VERSION" \
        -t "$PACKAGE_VERSION" \
        -n "$(cat CHANGELOG.md)
        
        ---

        使用方法，Chrome、Edge、Arc 用户请在 [Chrome 商店中安装](https://chromewebstore.google.com/detail/fbgblmjbeebanackldpbmpacppflgmlj)
        
        火狐浏览器用户点击链接下载安装包使用。[下载](https://github.com/dlzmoe/linuxdo-scripts/tree/main/.output)
        
        发布于：$CURRENT_DATE"
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Upload release assets
      if: env.create_release == 'true'
      run: |
        for file in .output/*; do
          gh release upload "$PACKAGE_VERSION" "$file"
        done
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
